### ISSUE TITLE
How to install/use addons from the repo?

### ISSUE THREAD

**Issue by mYnDstrEAm** [basilgello/kodi-nightly-debian-repo#2]
Under [What is Included](https://github.com/basilgello/kodi-nightly-debian-repo#what-is-included) a number of addons that are also hosted in this repo are listed. I have `kodi-visualization-spectrum` and `kodi-pvr-mythtv` installed. But I can't see them in the Addons tab in Kodi (nor in any other tab such as TV and Music).

How to use these and other included addons?

Furthermore, I also can't find any addons when I search for "PVR" and "visualization" in the Addons tab in Kodi.

It's probably not a bug and I'm just missing something simple.

**Comment by basilgello** [comment]
Did you navigate to All Addons browser? You will see categories and under "All Addons" you will see your newly-installed addons marked with "X" sign.
That means they are installed but disabled by default. Enter the addon and click "Enable" button. The "X" sign changes to a check-mark.

**Comment by mYnDstrEAm** [comment]
Under Addons -> User addons -> All I could find them now but not in the search, on the Addons page or on the Kodi TV and Music pages. Under all _Spectrum_, _MythTV PVR client_ and Reddit Reader are shown as deactivated. I did not deactivate them and did not get prompted or a popup related to them so why are they deactivated? And why didn't the search find them? I could activate Spectrum and MythTV PVR client but Reddit Reader is not compatible with this Kodi version. I can't find any reddit addons now. And why is the Spectrum addon still not shown under addons? How to use it? It doesn't get used when playing music. And why is there no entry for "PVR clients" under addons?

**Comment by basilgello** [comment]
> why are they deactivated?

it is a feature. Most add-ons require configuration, so user is expected to enable and configure them manually. See: https://forum.kodi.tv/showthread.php?tid=327763&pid=2701238#pid2701238

> And why didn't the search find them?

I think I need to ask ronie, enen1992 or howie-f why disabled add-ons don't get into search results. It is a bug very likely.

> How to use it? It doesn't get used when playing music.

Did you enable Spectrum under Settings - Player - Music - Visualization?

**Comment by mYnDstrEAm** [comment]
> it is a feature. Most add-ons require configuration, so user is expected to enable and configure it.

Ok, but in that case the user should be prompted for it or at least get a notification popup. And it shouldn't be so hard to find either but display somewhere very visibly and also in the search results. It's a Kodi issue I guess and I'm not sure if I'm allowed to create an issue for it as the repo only allows for bugs and this could only partly be considered a bug.

> I think I need to ask ronie, enen1992 or howie-f why disabled add-ons don't get into search results. It is a bug very likely.

I'll do some tests and will check if the logs show anything then I'll ask about it. When searching for "spectrum" (and "Spectrum") no results are shown even after enabling it. Same for "reddit" (Reddit Reader is still disabled).

> Did you enable Spectrum under Settings - Player - Music - Visualization?

No, thanks! How am I supposed to know that this has to be done and where exactly to find this setting? I think it would be better if users were prompted about things like this and if this could be enabled from within the addon's configuration or from within an entry under Addons (e.g. "Spectrum-Control") instead of relying on external, non-integrated guides (of which some probably also inform about this setting).

**Comment by basilgello** [comment]
> Ok, but in that case the user should be prompted for it or at least get a notification popup. And it shouldn't be so hard to find either but display somewhere very visibly and also in the search results. It's a Kodi issue I guess and I'm not sure if I'm allowed to create an issue for it as the repo only allows for bugs and this could only partly be considered a bug.

Fair point. Please raise an issue in xbmc/xbmc.

> How am I supposed to know that this has to be done and where exactly to find this setting? I think it would be better if users were prompted about things like this and if this could be enabled from within the addon's configuration or from within an entry under Addons instead of relying on external, non-integrated guides (of which some probably also inform about this setting).

This needs to be in a wiki. Can you please check it is there or not? If not, feel free to edit Wiki page.

**Comment by mYnDstrEAm** [comment]
> Fair point. Please raise an issue in xbmc/xbmc.

Done: https://github.com/xbmc/xbmc/issues/18739

> This needs to be in a wiki. Can you please check it is there or not? If not, feel free to edit Wiki page.

It's not in these pages [[1]](https://kodi.wiki/view/Add-on:Spectrum) [[2]](https://kodi.wiki/view/Add-on:MilkDrop_2). In fact these two pages seem to be either outdated or not describe the procedure for the Kodi 19.0 in your repo. Under Addons -> Download there is no entry for "Music visualizations" - only "Music". And there no music visualization addons are included.

Closing this issue as kodi-pvr-iptvsimple does work, as does the spectrum addon now. I created a separate issue for the Reddit Viewer addon (and the default controller): #3

**Comment by razihaider-694** [comment]
If you are asking about Installing about the Kodi addons, Then they are two methods of Installing,
1. First you can add the resource URL and then Install it
2. You can download the zip file and manually install the addon.

You can take a look at where the full tutorial is given. https://thefiresticktv.com/install-livehub-kodi-addon-free-iptv-kodi/

**Comment by mYnDstrEAm** [comment]
> If you are asking about Installing about the Kodi addons, Then they are two methods of Installing,
> 
>     1. First you can add the resource URL and then Install it
> 
>     2. You can download the zip file and manually install the addon.
> 
> 
> You can take a look at where the full tutorial is given. https://thefiresticktv.com/install-livehub-kodi-addon-free-iptv-kodi/

I wasn't asking about it. (I downloaded the zip, ran sha256sum ./..zip and then installed it from within Kodi by going to Addons -> Install from zip file)
